version: '3.6'
services:
  postgres:
    image: postgres:11.9
    container_name: hello-dude-postgres
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql